"""
Analyis and prediction with skrub data ops
"""

# %%
import skrub
import numpy as np
import polars as pl

# %%
data_all = pl.read_parquet("data/wowah_data_raw.parquet")

data = data_all.filter(
    pl.col("char").is_in(
        data_all.select(pl.col("char").unique())
        .sample(fraction=0.1, seed=42)["char"]
        .implode()
    )
)
data_with_churn = pl.read_parquet("data/wowah_user_month_with_churn.parquet").filter(
    pl.col("char").is_in(data.select(pl.col("char").unique())["char"].implode())
)

# %%
# Load the raw data
data_raw = skrub.var("raw_data", data).skb.subsample()
data_var = data_raw.with_columns(guild=pl.col("guild").replace({-1: None}))
# Load the churn data
data_churn = skrub.var(
    "churn_data", data_with_churn
).skb.subsample()  # I have to subsample here otherwise the apply with the
# model at the end complains that there is a difference in the size between
# X and y

# %%
from sklearn.model_selection import BaseCrossValidator
import numpy as np

# This splitter was generated by an agent
# I wanted to have a splitter that splits data by month. 
class TimeSeriesUserSplit(BaseCrossValidator):
    """
    Time series splitter for (uid, month) pairs.

    Splits data so that training set contains earlier months and
    test set contains later months, preventing data leakage in time series.

    Parameters
    ----------
    n_splits : int
        Number of splits to create
    test_months : int
        Number of months to use for test set (default: 1)
    gap : int
        Number of months to skip between train and test (default: 0)
    """

    def __init__(self, n_splits=12, test_months=1, gap=0):
        self.n_splits = n_splits
        self.test_months = test_months
        self.gap = gap

    def split(self, X, y=None, groups=None):
        """
        Generate (train_idx, test_idx) pairs for splitting.

        Parameters
        ----------
        X : polars DataFrame or array-like with 'char' and 'month' columns
        y : ignored, but required for sklearn compatibility
        groups : ignored

        Yields
        ------
        train_idx : ndarray
            Training set indices
        test_idx : ndarray
            Test set indices
        """
        # Convert to polars DataFrame if needed
        if isinstance(X, pl.DataFrame):
            X_df = X
        else:
            X_df = pl.DataFrame(X, schema=["char", "month"])

        # Get unique months sorted
        months = sorted(X_df["month"].unique().to_list())

        if len(months) < self.n_splits + self.test_months:
            raise ValueError(
                f"Not enough months ({len(months)}) for {self.n_splits} splits "
                f"with test_months={self.test_months}"
            )

        # Generate splits
        for i in range(self.n_splits):
            # Training uses months up to index i
            train_end_idx = i
            # Gap between train and test
            test_start_idx = train_end_idx + 1 + self.gap
            # Test uses next test_months
            test_end_idx = test_start_idx + self.test_months - 1

            if test_end_idx >= len(months):
                break

            train_months = months[:test_start_idx]
            test_months_set = months[test_start_idx : test_end_idx + 1]

            train_idx = np.where(X_df["month"].is_in(train_months).to_numpy())[0]
            test_idx = np.where(X_df["month"].is_in(test_months_set).to_numpy())[0]

            yield X_df[train_idx], X_df[test_idx], y[train_idx], y[test_idx]

    def split_X_y(self, X, y=None, groups=None):
        return self.split(X, y, groups)

    def get_n_splits(self, X=None, y=None, groups=None):
        return self.n_splits


splitter = TimeSeriesUserSplit(n_splits=11, test_months=1)

# X = data_churn.select("char", "month").skb.mark_as_X()
X = data_churn.select("char", "month").skb.mark_as_X(cv=splitter)
y = data_churn.select("churned").skb.mark_as_y()

## %%
from skrub import SessionEncoder

# %%
# Create a session encoder with a 30 minute timeout
encoder = SessionEncoder(group_by="char", timestamp_col="timestamp", session_gap=30)

data_with_sessions = data_var.skb.apply(encoder)
# %%
data_with_sessions
# %%
from skrub import deferred


@deferred
def add_session_features(df):
    return df.with_columns(
        pl.col("timestamp").first().over("timestamp_session_id").alias("session_start"),
        pl.col("timestamp").last().over("timestamp_session_id").alias("session_end"),
        pl.col("level")
        .max()
        .over("timestamp_session_id")
        .alias("max_level_in_session"),
        pl.col("level")
        .n_unique()
        .over("timestamp_session_id")
        .alias("levels_in_session"),
        pl.col("zone")
        .n_unique()
        .over("timestamp_session_id")
        .alias("zones_in_session"),
    )


@deferred
def add_char_features(df):
    return df.with_columns(
        pl.col("timestamp").first().over("char").alias("char_first_seen"),
        pl.col("timestamp").last().over("char").alias("char_last_seen"),
        pl.col("level").max().over("char").alias("max_level"),
        pl.col("zone").n_unique().over("char").alias("unique_zones_visited"),
        pl.col("timestamp_session_id").count().over("char").alias("sessions_per_char"),
        pl.col("timestamp_session_id")
        .count()
        .over("timestamp_session_id")
        .alias("session_duration"),
        pl.col("guild").n_unique().over("char").alias("guilds_joined"),
    )


@deferred
def add_aggregated_features(df):
    return df.with_columns(
        pl.col("level").mean().over("race").alias("avg_level_by_race"),
        pl.col("level").mean().over("charclass").alias("avg_level_by_class"),
        pl.col("level").mean().over("guild").alias("avg_level_by_guild"),
        pl.col("level").mean().over("zone").alias("avg_level_by_zone"),
        pl.col("charclass").count().over("charclass").alias("count_by_charclass"),
        pl.col("race").count().over("race").alias("count_by_race"),
        pl.col("char")
        .count()
        .over("race", "charclass")
        .alias("count_by_race_charclass"),
    )


# %%
data_with_all_features = (
    data_with_sessions.skb.apply_func(add_session_features)
    .skb.apply_func(add_char_features)
    .skb.apply_func(add_aggregated_features)
)
# %%
from skrub import TableVectorizer
import skrub.selectors as s

# %%
# It would be *very* convenient to have the except argument here
data_vectorized = data_with_all_features.skb.apply(
    TableVectorizer(), cols=s.all() - "char" - "timestamp"
).skb.set_name("data_vectorized")
# %%
# After vectorization, I'm aggregating the data by month since I have the 
# churn labels by month. I'm taking the mean of the features for each month
# Here we could go with a choose_from and different agg functions
data_monthly = (
    data_vectorized.with_columns(month=pl.col("timestamp").dt.truncate("1mo"))
    .group_by("char", "month")
    .agg(pl.all().mean())
)

# %%
data_monthly_with_churn = data_monthly.join(X, on=["char", "month"], how="inner")
data_monthly_with_churn
# %%
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier(n_estimators=100, random_state=42)

pred = data_monthly_with_churn.skb.apply(model, y=y).skb.set_name("churn_model")

# %%
learner = pred.skb.make_learner(fitted=True)

# %%
# Here I don't get how I am supposed to pass the splitter 
cv_results = pred.skb.cross_validate(
    environment={"raw_data": data, "churn_data": data_with_churn},
    # cv=splitter,
    scoring=["precision", "recall", "f1", "roc_auc"],
)

# %%
tts = TimeSeriesUserSplit(n_splits=2, test_months=1)

# trying to get train and test splits so that I can measure the performance of 
# the model at the end
pred.skb.train_test_split(split_func=tts.split)
# %%
# In the end I gave up and defined the splits manually
train_months = X["month"].unique().skb.eval()[:-1]
test_months_set = X["month"].unique().skb.eval()[-1:]
train_idx = np.where(X["month"].skb.eval().is_in(train_months).to_numpy())[0]
test_idx = np.where(X["month"].skb.eval().is_in(test_months_set).to_numpy())[0]


# %%
def split(X, y, train_idx, test_idx):
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]

splits = pred.skb.train_test_split(
    split_func=split, train_idx=train_idx, test_idx=test_idx
)
# %%
